# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-16 19:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialGlobo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 16, 19, 56, 0, 913031))),
            ],
            options={
                'verbose_name': 'historialgLobo',
                'db_table': 'historial_globo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=1000)),
                ('password', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'GLobo',
                'db_table': 'globo',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='historialglobo',
            name='usuario',
            field=models.ForeignKey(blank=True, db_column='usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Usuarios'),
        ),
    ]
