# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-16 20:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Estado',
                'db_table': 'estado',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='historialglobo',
            options={'managed': True, 'verbose_name': 'Historial Globo'},
        ),
        migrations.AlterModelOptions(
            name='usuarios',
            options={'managed': True, 'verbose_name': 'Globo'},
        ),
        migrations.AlterField(
            model_name='historialglobo',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 16, 20, 10, 46, 146645)),
        ),
        migrations.AddField(
            model_name='historialglobo',
            name='estado',
            field=models.ForeignKey(blank=True, db_column='estado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Estado'),
        ),
    ]
