# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-21 00:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180816_2010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuarios',
            options={'managed': True, 'verbose_name': 'Usuarios'},
        ),
        migrations.AddField(
            model_name='historialglobo',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 21, 0, 42, 53, 428680)),
        ),
        migrations.AddField(
            model_name='historialglobo',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 21, 0, 42, 53, 428641)),
        ),
        migrations.AlterField(
            model_name='historialglobo',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 21, 0, 42, 53, 428585)),
        ),
    ]
