# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-01-04 22:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180824_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='Whatsapp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=1000)),
                ('fecha', models.DateTimeField(blank=True, default=datetime.datetime(2019, 1, 4, 17, 9, 32, 468635))),
                ('usuario', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterModelOptions(
            name='usuarios',
            options={'managed': True, 'verbose_name': 'Usuario'},
        ),
        migrations.AlterField(
            model_name='historialglobo',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 1, 4, 17, 9, 32, 469507)),
        ),
        migrations.AlterField(
            model_name='historialglobo',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 1, 4, 17, 9, 32, 469601)),
        ),
        migrations.AlterField(
            model_name='historialglobo',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 1, 4, 17, 9, 32, 469553)),
        ),
    ]
