# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-01-15 18:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190104_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsapp',
            name='fecha_mensaje',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 15, 13, 33, 21, 665398)),
        ),
        migrations.AddField(
            model_name='whatsapp',
            name='grupo',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='historialglobo',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 1, 15, 13, 33, 21, 666233)),
        ),
        migrations.AlterField(
            model_name='historialglobo',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 1, 15, 13, 33, 21, 666308)),
        ),
        migrations.AlterField(
            model_name='historialglobo',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 1, 15, 13, 33, 21, 666273)),
        ),
        migrations.AlterField(
            model_name='whatsapp',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 1, 15, 13, 33, 21, 665134)),
        ),
        migrations.AlterField(
            model_name='whatsapp',
            name='mensaje',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='whatsapp',
            name='usuario',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
